version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-app
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-app
    volumes:
      - ./app:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: sh start.sh
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=owner 
    networks:
      - node-app

networks:
  node-app:
    driver: bridge